### ISSUE TITLE
一直显示not found 最后fail

### ISSUE THREAD

**Issue by udpsec** [OXOYO/bookmark2md#1]

**Comment by OXOYO** [comment]
not found 是info级，提示reop/branch下并没有该md文件。
fail 是error级，提示按当前规则可以生成多少个md文件，push成功多少个，失败多少个。

出现fail,建议再次push，直到fail为0。

另外，可以直接通过chrom扩展程序，加载Extension目录为已解压的扩展程序，然后打开扩展程序选项进行调试。

之前有遇到fail是由于github api出现409错误导致，可以贴出具体的debug错误再做分析。

欢迎fork pr修复bug。
